services:

  db:
    image: postgres:15
    container_name: fintrack_test_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrack
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  backend:
    build: ./
    container_name: fintrack_test_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fintrack
      ENV: test
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: fintrack_test_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_test_data: