"""update categ - expenses relation

Revision ID: 1247161e2025
Revises: ca76eb3b5734
Create Date: 2026-05-16 10:25:26.757055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1247161e2025'
down_revision: Union[str, Sequence[str], None] = 'ca76eb3b5734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'categories', ['category_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'category_name')
    # ### end Alembic commands ###
