"""add refresh_tokens table

Revision ID: 1845502724f8
Revises: b382c1324a72
Create Date: 2026-05-11 10:47:29.576950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1845502724f8'
down_revision: Union[str, Sequence[str], None] = 'b382c1324a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('hashed_token', sa.String(), nullable=False))
    op.drop_column('refresh_tokens', 'hash_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('hash_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'hashed_token')
    # ### end Alembic commands ###
