"""add expenses table

Revision ID: ab6fcdc2ba19
Revises: 019c8776014e
Create Date: 2026-05-13 10:30:16.014355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab6fcdc2ba19'
down_revision: Union[str, Sequence[str], None] = '019c8776014e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('transaction_date', sa.DateTime(), nullable=False))
    op.drop_column('expenses', 'transcation_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('transcation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('expenses', 'transaction_date')
    # ### end Alembic commands ###
