"""update categ - expenses relation

Revision ID: d451345e0f52
Revises: fe03d47103b9
Create Date: 2026-05-16 11:20:52.200507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd451345e0f52'
down_revision: Union[str, Sequence[str], None] = 'fe03d47103b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
