"""update categ - expenses relation

Revision ID: ea92eac91dcb
Revises: 1247161e2025
Create Date: 2026-05-16 11:00:44.962482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea92eac91dcb'
down_revision: Union[str, Sequence[str], None] = '1247161e2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_category_name', 'categories', ['user_id', 'name', 'is_deleted'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_category_name', 'categories', type_='unique')
    # ### end Alembic commands ###
