"""update categ - expenses relation

Revision ID: fe03d47103b9
Revises: ea92eac91dcb
Create Date: 2026-05-16 11:09:28.872929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe03d47103b9'
down_revision: Union[str, Sequence[str], None] = 'ea92eac91dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category_name')
    # ### end Alembic commands ###
